### ISSUE TITLE
Shade UI - OS X

### ISSUE THREAD

**Issue by sigwo** [syscoin/syscoin2#1]
Upon losing focus, the menu drop downs should shrink.
There should be max width proportionate to the main window size.
![screen shot 2016-02-29 at 12 43 35 pm](https://cloud.githubusercontent.com/assets/205676/13403248/1dc4f606-dee2-11e5-9ea3-37cb527069f8.png)
Just me, but I would move the 'New Alias' button to the far left. 
![screen shot 2016-02-29 at 12 44 49 pm](https://cloud.githubusercontent.com/assets/205676/13403286/3ecf4ca2-dee2-11e5-85db-b5b072d0c54b.png)

**Comment by sigwo** [comment]
Wrong description in the box next to 'New Certificate', also consider moving all 'New <blank>' buttons to the far left. We read left -> right. :)
![screen shot 2016-02-29 at 3 44 37 pm](https://cloud.githubusercontent.com/assets/205676/13408395/a16bf540-defb-11e5-923b-9d5e80162b05.png)

**Comment by sidhujag** [comment]
fixed second part in latest build

**Comment by sidhujag** [comment]
moved buttons to far left

**Comment by sebastien1234** [comment]
@sigwo I'm testing in windows, there's no menu drop down, I believe this issue is completely resolved, can we close #1?

**Comment by sigwo** [comment]
Yup. Looks good.
