### ISSUE TITLE
Image issue with offer (JPG)

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#10]
Issue with picture(JPG) only partially appearing

This one is a little different, a blue square appears but not the actual image
GUID:   00d0d174b27fe20f:
this is the link and it works fine in a browser. 

Image included in text is the following:
http://i2.wp.com/syscoin.org/wp-content/uploads/2015/07/Navy-ShrtSlv-LogoOnly-Front.jpg?fit=300%2C250

I've also tried duplicating the issue via GUID: 17050c5a079f5a72, but removing the ?fit=300%2C250 end, but still same problem.

This is what appears:

![image](https://cloud.githubusercontent.com/assets/7034589/13413629/00090110-df1a-11e5-8aec-9471569b1a0b.png)

**Comment by sebastien1234** [comment]
@sidhujag this problem is still happening latest 3/7/2016 build.

**Comment by sebastien1234** [comment]
@sidhujag this problem is still happening latest 3/12/2016 build.

**Comment by sebastien1234** [comment]
@sidhujag Issue still happening on 3/17 build

**Comment by sebastien1234** [comment]
@sidhujag issue remains in 6/18 2.1 alpha build.

**Comment by sebastien1234** [comment]
@sidhujag this issue remains in 9/9 build, fyi same issue happens when you remove the resizing of the pic as link below:

http://i2.wp.com/syscoin.org/wp-content/uploads/2015/07/Navy-ShrtSlv-LogoOnly-Front.jpg

**Comment by willyko** [comment]
Closing this issue since offer features has been moved to Blockmarket
