### ISSUE TITLE
make error help!

### ISSUE THREAD

**Issue by fusenn** [syscoin/syscoin2#103]
/home/blue/Downloads/syscoin2-2.0/src/test/rpc_wallet_tests.cpp:65: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case_, boost::unit_test::decorator::collector&, unsigned long)'
collect2: error: ld returned 1 exit status
Makefile:3493: recipe for target 'test/test_syscoin' failed
make[2]: *_\* [test/test_syscoin] Error 1
make[2]: Leaving directory '/home/blue/Downloads/syscoin2-2.0/src'
Makefile:8885: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/blue/Downloads/syscoin2-2.0/src'
Makefile:648: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

Anyone know why make compile is failing?
ubuntu 16.04 x64

**Comment by sidhujag** [comment]
Did you follow the build instructions under docs? Are you able to build bitcoin at all?

**Comment by fusenn** [comment]
Yes I did follow build instructions, did autogen.sh, then configure with additional arguments from docs, then make, and that is the error i get when trying to make.

**Comment by sidhujag** [comment]
So you have boost fully installed? Try bitcoin see if you get same message. You can always build without tests to get past that error too..the instructions show how to do that.

**Comment by fusenn** [comment]
I can't see in the instructions how to build without tests, can you tell me the cmd please?

**Comment by sidhujag** [comment]
Hey man,

try ./configure --disable-tests

**Comment by willyko** [comment]
Closing this issue; We're on 2.1.6 version now
