### ISSUE TITLE
should not allow creating multiple aliases within same block

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#105]
Testing for 9/8/2016 build ; windows 10:

Test case:

Created alias: sebastien
tried to create alias: SEBASTIEN

as I tried to create the alias right away, I was on the same block and did not get an error message preventing me from using the alias. Instead, I was charged twice to activate the same lowercase alias (although the second fee was a fraction of the amount). 

If we are not going to allow multiple features in the same block, then I suggest there be a mechanism to prevent a user from performing more than one action. Personally, I think this limits considerably usability if we limit to 1 transaction per block.

![image](https://cloud.githubusercontent.com/assets/7034589/18407646/49345d90-76e5-11e6-9188-195e32c864ae.png)

**Comment by sidhujag** [comment]
it just recreates the alias everytime until it confirms... theres no issue here I believe.. the mempool checks were all taken out as those were hacks. If you do an aliasinfo on it you will see it uses the last tx you created

**Comment by sebastien1234** [comment]
The test case here @sidhujag is that I tried to create two of the same alias(one lowercase and one uppercase to first test the fact that it should all default to lowercase), it charged me for both even though it obviously is only creating one.

**Comment by sidhujag** [comment]
aliases are now case insensitive and are lowercase, so essentially you were creating the same alias again... thats why you noitce that it shows two "sebastien" aliases created in your tx history

**Comment by sebastien1234** [comment]
correct, that's why I'm suggesting that there's a mechanism to prevent you from doing that as this is now all block sensitive I did not get an error message (I do if I wait the block though)

**Comment by sidhujag** [comment]
only way is to do the mempool check which I removed... its probably just best to document it as a "how it works" I doubt many people will waste fees trying to create multiple times and if they do they wont complain because they will have done it knowingly

**Comment by sebastien1234** [comment]
latest build resolves this issue. close #105

**Comment by sebastien1234** [comment]
issue still happens but since you cannot create aliases with uppercase the impact is minimal.
