### ISSUE TITLE
Changes to reputation system required

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#106]
Currently the reputation system looks great, however, a few tweaks are required:

-We need to be able to differentiate between buyer/seller/arbiter as they are obviously very different roles. A person could be a good buyer but a first-time horrible merchant, we should be able to see the following on an aliases profile:

-rating for each role (buyer/arbiter/seller)
-the amount of ratings per role
-the comments associated with those reviews

**Comment by sidhujag** [comment]
Because lack of space I just averaged the ratings. The amount I just added together and the reivews are all inline... I seperated the feedbacks per role on the RPC side so BM can easily do this.

**Comment by sidhujag** [comment]
please test in testnet 2b.... rating for each role and amount are shown on alias page

**Comment by sebastien1234** [comment]
close #106
