### ISSUE TITLE
Failed to connect to the best block

### ISSUE THREAD

**Issue by banjochose** [syscoin/syscoin2#117]
Happendall the time tried to sync at least 3 times from scratch , my OS is described bellow by the way tried also over wine to run windows version it sync well but after I restart and run it again it always give an error mentioned in title and wont start.

This happens with official release syscoin 2

in folder .syscoin/debug.log
-------------------
de61 failed
2016-12-09 17:25:21 ERROR: ConnectTip(): ConnectBlock 597086c9a7298bc6e87307390538d0aa7fbfbf565dcde9d4ae6bcde8934ae9af failed
2016-12-09 17:25:21 ERROR: ProcessNewBlock: ActivateBestChain failed
2016-12-09 17:25:21 *** 1697 1696 e2bc7f6dea0fb0c019b6344fa6439920f4cc96c2048986d138b76d693cbade61 JUSTCHECK
2016-12-09 17:25:21 ERROR: CheckMessageInputs() OP_MESSAGE_ACTIVATE: alias and message from pubkey's must match
2016-12-09 17:25:21 ERROR: ConnectBlock(): CheckSyscoinInputs on e2bc7f6dea0fb0c019b6344fa6439920f4cc96c2048986d138b76d693cbade61 failed

###############################
root@localhost:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
##########################################
root@localhost:~# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
###################################
root@localhost:~# openssl version -a
OpenSSL 1.0.1f 6 Jan 2014
built on: Fri Sep 23 12:19:57 UTC 2016
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: cc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/lib/ssl"
##############

**Comment by sidhujag** [comment]
plz wait until 2.1 on the 18th

**Comment by banjochose** [comment]
So it doesn't work at the current time am I right ? some other solution How I could tackle with it myself?

**Comment by banjochose** [comment]
I am also confused from your answer you mean that at 2.1.2017 it will begin to work properly ?

**Comment by sidhujag** [comment]
a 2.1 release will fix all current issues due to be released on the 18th of this month
