### ISSUE TITLE
updating expired alias that had password with a new password does not work

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#118]
Tried to update expired alias (which originally had a password) and changing password at the same time, received the following error message:

![errorpassword](https://cloud.githubusercontent.com/assets/7034589/21075496/a34caa5a-bee1-11e6-803d-50a909cb38e9.PNG)

Also tried to renew alias without putting a password and it worked, then tried to update alias with password, received same error message.

**Comment by sidhujag** [comment]
Did you already use that password in that wallet? It would give that error if that password alias combination was already used.. ive since changed it to check and throw that only if password is not found in wallet

**Comment by sebastien1234** [comment]
fixed close #118
