### ISSUE TITLE
from search, double-clicking offer that's selling certificate, makes you pay for it before seeing details

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#12]
marketplace/search

After searching and listing offers, double clicking on a displayed offer, right away, it brings you to the "are you sure you want to purchase" screen. It should first bring you to the "Buy" screen so you can see the full offer.

@sidhujag FYI, this is only happening when offers have certificates attached.

Tranferring issue from syscoin 1 to syscoin 2; Issue not yet resolved with March 6th Build. 
https://github.com/syscoin/syscoin/issues/122

**Comment by sebastien1234** [comment]
@sidhujag this bug is still happening on the latest 3/7/2016 build

**Comment by sebastien1234** [comment]
@sidhujag this bug is still happening on the latest 3/12/2016 build

**Comment by Keyare** [comment]
@sidhujag this bug is still happening on the latest 3/17/2016 build

**Comment by sebastien1234** [comment]
@sidhujag I can confirm also, bug still present

**Comment by sebastien1234** [comment]
@sidhujag I can confirm also, bug still present in 6/18 2.1 alpha build.

**Comment by sebastien1234** [comment]
@sidhujag I can confirm error still present in 9/9 build.

**Comment by willyko** [comment]
Closing this issue since offer feature has been moved to Blockmarket
