### ISSUE TITLE
searches for aliases, certificates, offers, all show different listings for two different computers

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#120]
PC1:

Aliases:
![image](https://cloud.githubusercontent.com/assets/7034589/21075817/84ebc98a-bee9-11e6-928b-01ff075ab5a3.png)

Offers:

![image](https://cloud.githubusercontent.com/assets/7034589/21075825/c4ce273c-bee9-11e6-90b6-32322e76bcd2.png)

certs:
![image](https://cloud.githubusercontent.com/assets/7034589/21075828/ddb7429c-bee9-11e6-9f49-8db1cfc35cfb.png)

PC2:

Aliases:
![image](https://cloud.githubusercontent.com/assets/7034589/21075847/598f49a0-beea-11e6-8f3c-921dee0f8682.png)

Offers:
![image](https://cloud.githubusercontent.com/assets/7034589/21075851/8ec42dfc-beea-11e6-81ac-93d7d1817695.png)

Certs:
![image](https://cloud.githubusercontent.com/assets/7034589/21075855/ac84b9f6-beea-11e6-9687-e484a6defcae.png)

**Comment by sidhujag** [comment]
wheres PC2?

**Comment by sebastien1234** [comment]
coming

**Comment by sebastien1234** [comment]
@sidhujag

**Comment by sidhujag** [comment]
What block are they on can you show blk number and try again as sanity?

**Comment by sebastien1234** [comment]
@sidhujag 

PC1: block: 2867

PC: block: 2960

**Comment by sidhujag** [comment]
ok first problem is why they on different block numbers, is PC1 stuck? check log? once they are on the same block can you redo test?

**Comment by sebastien1234** [comment]
fixed close #120
