### ISSUE TITLE
wrong error when trying to create an existing alias

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#122]
tried to create alias buyer but someone already had it, received the following error message, should instead say "Error Creating New Alias: This alias already exists"

![image](https://cloud.githubusercontent.com/assets/7034589/21169157/ba709216-c187-11e6-976d-6ec61c056dac.png)

**Comment by sidhujag** [comment]
What should it have said?

**Comment by sebastien1234** [comment]
Sorry was sure I pasted the image, see the error, should instead say : "Error Creating New Alias: This alias already exists"

**Comment by sidhujag** [comment]
retest

**Comment by sebastien1234** [comment]
works, close #122
