### ISSUE TITLE
reseller info does not show price of sold offer, just commission

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#126]
Original offer 1 SYS

Reseller gets a discount of %50

Reseller resells offer at %45

Resold offer gets purchased

In "sold" tab, in "price" it only indicates the commission that the reseller made and not the actual price he sold it at.

**Comment by sebastien1234** [comment]
![image](https://cloud.githubusercontent.com/assets/7034589/21295423/dfeffd4e-c522-11e6-9ddd-33f930ffa473.png)

**Comment by sidhujag** [comment]
that is the design, the reseller sees how much he made out of the sale

**Comment by sebastien1234** [comment]
close #126
