### ISSUE TITLE
New Public Key for Alias Runaway Error

### ISSUE THREAD

**Issue by codethejason** [syscoin/syscoin2#129]
When the wallet is unencrypted, generating a new public key produces a runaway exception that terminates the application (syscoin-qt.exe has stopped working). There should be a soft error to prevent the application from crashing or a notice to unencrypt the wallet using walletpassphrase.

![error](http://puu.sh/t5bbg/5ad6d2c8eb.png)

Windows 10 x64

**Comment by sidhujag** [comment]
This has been fixed slated for 2.1.2 release
