### ISSUE TITLE
Date/time required in Marketplace columns / enhancement

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#13]
Marketplace/(selling, sold, my purchases, search, buy) should all have dates with times in the first column.

Accept ID and Blockheight are not necessary to be shown (it will just confuse people and you can still check this info by doing right-click/details). These fields should be replaced by date and time.

Closing 77 from syscoin 1 and putting here.

**Comment by sebastien1234** [comment]
This issue is still present in latest 3/7/2016 build @sidhujag

**Comment by sebastien1234** [comment]
issue #13 still present, @sidhujag it's pretty important to have the dates in here.

**Comment by sebastien1234** [comment]
issue #13 still present in 6/18 build, @sidhujag it's pretty important to have the dates in here.

**Comment by sebastien1234** [comment]
@sidhujag issue still present in 9/9 build, as indicated it's very important to have dates in there, only block heights are indicated and transactions don't indicate blockheight (and even if transactions included blockheight, it would be extremely tedious for a merchant to find the time the transaction occurred.) This issue is very important for merchant records.

**Comment by willyko** [comment]
Closing this issue since marketplace UI has been moved to Blockmarket
