### ISSUE TITLE
Need more efficient RPC method for fetching updated alias info

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin2#142]
There is no way to get updated alias info from the RPC until at least 1 confirm has occured. This differs from aliasnew which can be fetched from aliaslist while the tx is still pending. Because of this difference, updating aliases in BM Desktop requires "polling" aliaslist for oldAliasValue != returnAliasListValue which slows down the UX of updating aliases dramatically.

Propose we update core to handle these updates the same way aliasnew/aliaslist works which provide immediate feedback.

**Comment by sidhujag** [comment]
for now i suggest putting refresh button as the txlist also will not auto update. This is a more involved task to add local entries into tables prior to confirmation and depending on core for wallet related information will break compatibility with bm web.

**Comment by dwasyluk** [comment]
I'll keep the polling solution as a refresh button would be poor UX and the goal of BM is best UX possible. Will add a refresh button as a sanity check but until fixes alias/cert/offer update will poll until confirms occur then the user will be notified the tx succeeded and it will appear updated in the respective lists without the need to click a refresh button on every screen. Let's keep this open until we can implement a better core solution.

**Comment by sidhujag** [comment]
This will need to be a UI design issue as the core will not be supporting transactions that are based on the wallet and not the chain... so we can make it nicer by simply showing a realtime UI log of polling transactions waiting for confirmation.

**Comment by sidhujag** [comment]
Unless txindex is used and then we poll for a transaction and get info on it related to a service.. that might also work

**Comment by dwasyluk** [comment]
Yep that works, then as discussed we have a mechanism in UI to notify user background activity is occurring waiting for confirms w lil spinny, then when we get confirms it goes away, display notification, etc. They can leave the edit page while this is occuring because the job is managed in the `walletDataService` not in the UI component submitting the edit :) can probably close this since no core-action is needed here.
