### ISSUE TITLE
client on linux with qt5 doesn't resize

### ISSUE THREAD

**Issue by arisAlexis** [syscoin/syscoin2#143]
build from sources 2.1.4 with qt5 the client opens up correctly but doesn't resize and takes up more that the screen size so it's impossible to see the status bar on the bottom.

**Comment by sidhujag** [comment]
dont care about qt anymore

**Comment by arisAlexis** [comment]
what do you mean by this? this is not really a professional or developer's way to close tickets. i have letig problems running the client on linux

**Comment by sidhujag** [comment]
We are moving onto to a new wallet (block market desktop) which will replace QT except for when you need to use things like coin control etc, it will be for minority users

**Comment by arisAlexis** [comment]
will this work on linux? if yes then i will wait

**Comment by sidhujag** [comment]
currently bm desktop doesnt work for linux but we just need to make a wrapper that will work I think there is a plan in place for it, but bm web will work regardless (if you are using a single alias then it should serve your purpose)

**Comment by arisAlexis** [comment]
i just want to have secure holding of my syscoin on my linux, if i use the product windows is fine. it's crypto linux should be supported if you change the wallet

**Comment by sidhujag** [comment]
yea and it does work in qt, just have to live with the resizing issue, i think you can maximize and it fixes (also happens in windows 10)
