### ISSUE TITLE
alias payment received

### ISSUE THREAD

**Issue by cap-tain** [syscoin/syscoin2#162]
hello made an sys coin transfer from exchange to wallet 2.1.6 and received my coins although showed up as alias payment description (jelmer). https://chainz.cryptoid.info/sys/tx.dws?616540.htm is the transactions. mod in slack said: "it looks like the address the 'jelmer' alias is connected to was also in the same block as your transaction" and "so possibly an issue with how the new wallet displays sender address details". so please have look at it. ty captain

**Comment by sidhujag** [comment]
So your address was 1Nzp2qQxu9487Xx3TkCTxhqpDdv44m6rNB? can you do validateaddress on the qt command console and see if an alias is returned in that response?

**Comment by cap-tain** [comment]
No my address was 19TYaMa1i8Mo7RB1rcpGZtmBL82MsbNnVq. command: validateadress; response: .... "alias":"", .....

**Comment by sidhujag** [comment]
oh ok yea polo sent it to 2 people in the same transaction and jelmer was the other guy.. its fine.. just that it parsed the transaction and found an alias payment it incorrectly identifies it as jelmer for you, wont be an issue in bm web.

**Comment by cap-tain** [comment]
ok then everything is fine i guess
