### ISSUE TITLE
TestNet RC1

### ISSUE THREAD

**Issue by johnp1954** [syscoin/syscoin2#167]
With the Testnet version of QT automatic backups are created, some users may not want this. You are supposed to be able to add -createwalletbackups=0 in the conf file to switch this off. This does not work. Can this be fixed. https://dashpay.atlassian.net/wiki/spaces/DOC/pages/1867878/How+to+safely+back+up+your+wallet

**Comment by sidhujag** [comment]
It only keeps the last 10 anyways

**Comment by johnp1954** [comment]
Ignore this, it works perfectly.
