### ISSUE TITLE
Messaging enhancements

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#17]
messages/(inbox/outbox):

Although the encrypted messaging is an amazing feature, it is tedious to deal with having a conversation with someone. Having to see what you wrote in your outbox and checking your inbox is not efficient and user-friendly.

Should have sections in messaging that shows the thread between two people from whenever they had a conversation from the start. If possible, should look similar to an SMS format where the bubble on the left is the person sending you a message and the buble on the right is your messages.

If possible also, would be great to have a small non-intrusive beep every time you receive a message.

**Comment by sebastien1234** [comment]
still an issue with the 3/17 build @sidhujag

**Comment by sebastien1234** [comment]
issue #17 still present in build 6/18 @sidhujag

**Comment by willyko** [comment]
Closing; Message function's UI has been moved to Blockmarket
