### ISSUE TITLE
make reselling easier to use

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#18]
Instead of having to transfer a reselling certificate manually to a re-seller, the wholesaler should simply be able to click a button or right click "Authorize Re-seller" which would simply open a dialog box that asks you for the name of the alias you want to give a discount to and the discount amount. After doing that, the wallet would automatically send the certificate to the reseller (within a few confirmations).

That way, we can auto-populate the certificate with the discount % that the reseller will receive because right now, re-sellers have no idea how much discount they receive until they try to use it.

**Comment by sidhujag** [comment]
What if we used aliases instead of certs for whitelists? no need to transfer to reseller.

**Comment by sebastien1234** [comment]
Yes, much easier, however we still don't know how much discount we get as an affiliate. close #18
