### ISSUE TITLE
Re-selling editing, price and qty should be grayed-out

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#26]
Tried to edit item I'm reselling

![image](https://cloud.githubusercontent.com/assets/7034589/13694727/4418a13a-e726-11e5-807b-ca9874b0cff7.png)

Form appears to allow you to edit the price and quantity.

Tried to edit offer to 0.05 SYS and Quantity to 300, it let me send the update but after confirmation came, nothing changed at all.

@sidhujag Price and Quantity should be grayed-out for re-sellers if you cannot make this change.

**Comment by willyko** [comment]
Closing this.  Offer function's UI has been moved to Blockmarket.
