### ISSUE TITLE
Unable to sell at lower price

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#28]
Situation:

Seller gives whitelist to re-seller and gives a 50% discount

Re-seller makes his money because he can give a better price than original reseller

Re-seller attempts to charge a lower price (10%) than what the market price is

Re-seller get's the following error message:

![image](https://cloud.githubusercontent.com/assets/7034589/13695160/eb2d0918-e729-11e5-8d9a-05b5de8c088e.png)

Reseller should be able to charge lower than the market price (just not lower than the discount he's getting).

**Comment by sidhujag** [comment]
fixed in latest, retest
