### ISSUE TITLE
reseller offer doesn't show certificate

### ISSUE THREAD

**Issue by sidhujag** [syscoin/syscoin2#29]
the reseller offer doesn't show the certificate if its  acert being sold... also if the root offer owner transfers the cert before the reseller offer is accepted, it will tak ethe money and  buyer gets no cert.

**Comment by sidhujag** [comment]
fixed in latest, sebastien please test this. Reseller offers shows certificate and if the root owner transfers the cert, the resold offer cannot be bought (buyer gets an error on accept)

**Comment by sebastien1234** [comment]
@sidhujag 

Reseller does not show certificate is linked to offer, see image below:

![image](https://cloud.githubusercontent.com/assets/7034589/13908580/c90e7452-eedb-11e5-96c5-eef67d240c3d.png)

**Comment by sebastien1234** [comment]
![image](https://cloud.githubusercontent.com/assets/7034589/13908590/16392a56-eedc-11e5-940e-3213c81cee41.png)

**Comment by sebastien1234** [comment]
![image](https://cloud.githubusercontent.com/assets/7034589/13908592/1ca15bca-eedc-11e5-910a-bc497697089c.png)

**Comment by sidhujag** [comment]
I see the cert right there at the bottom?

**Comment by sebastien1234** [comment]
close #29
