### ISSUE TITLE
Change reseller error when tries to sell less than discount he received

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#35]
marketplace/search/resell/resell offer:

When trying to resell at a higher discount than received, you get the following error message:

![image](https://cloud.githubusercontent.com/assets/7034589/13731316/41dd18ac-e93c-11e5-96d9-ad6bee701a7d.png)

Error message should be change to the following:

"You cannot re-sell at a lower price than the discount you received as an affiliate (current discount received: 10%)"

**Comment by sidhujag** [comment]
Did you mean when the commission is less than discount? The error screenshot isn't there but I know what you mean.

**Comment by sebastien1234** [comment]
yeah you could see it like that too, price of item is less than the discounted price you received from the original seller

**Comment by willyko** [comment]
Closing this.  Resell function has been deprecated
