### ISSUE TITLE
Pegging not accurate

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#37]
Price pegger not accurate, currently an offer of 1 USD costs 2690.10 SYS

![image](https://cloud.githubusercontent.com/assets/7034589/13906156/2a98e7ba-eea6-11e5-82fc-809a8ddfd7c7.png)

**Comment by sidhujag** [comment]
isn't 1 USD 2690.1 sys in the price peg?

**Comment by sebastien1234** [comment]
it's not but I'll close #37 since it was discussed on chat that it's currently set to that and will be updated.
