### ISSUE TITLE
Two affiliates cannot resell same offer

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#40]
Create an offer

Add Arbiter#1 to offer

Arbiter#1 resells offer

Seller adds Arbiter #2 

Arbiter #2 tries to sell offer and gets this message(even if offer update was confirmed):

![image](https://cloud.githubusercontent.com/assets/7034589/13906459/c1b7f716-eeac-11e5-82fe-9d73b770fa16.png)

**Comment by sidhujag** [comment]
you can't link against an offer that is already linked. Is that what is happening?

**Comment by sebastien1234** [comment]
Yes, that's right

**Comment by sebastien1234** [comment]
so it appears only one affiliate per offer is possible

**Comment by sidhujag** [comment]
yes per design
