### ISSUE TITLE
Arbiter should get a bigger cut

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#42]
Currently the Arbiter gets a very small amount of sys 0.00000603.

This is not sustainable, it's not worth the time to even click on it.

Suggestion that Arbiter gets a cut of the sale so it does not pay him in network fees but from a cut of the sale (if escrow is selected, price increases by 2% which the buyer accepts as a markup.

**Comment by sebastien1234** [comment]
![image](https://cloud.githubusercontent.com/assets/7034589/13908127/f10eefe4-eed2-11e5-865c-9adaad848b43.png)

**Comment by sidhujag** [comment]
that is exactly what should be happening but i think its 0.05%  we can make that variable, not sure how the flow would work yet on that.

**Comment by sebastien1234** [comment]
closing #42 opened #48 to replace it
