### ISSUE TITLE
Certificate sale escrow flaw

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#44]
Test: Resell escrow with certificate
Buyer releases escrow, then seller does, 
Cert is received, arbiter does not need to do anything, 
Reseller did not need to do anything, got his commission,

The flow works properly, however, there is a major flaw here, if the cert needs to be transferred after the escrow is released,
then how does the arbiter know who to side with, it seems pointless to have escrow for selling certs.

**Comment by sidhujag** [comment]
the owner transfers cert manually before buyer releases.. i put in code to deal with a manual xfer.. seller xfers manually and then buyer releases

**Comment by sidhujag** [comment]
buyer will never release if they dont get something so seller usually will xfer manually

**Comment by sebastien1234** [comment]
But in a dispute, there is really no way for the Arbiter to know if the sale was legit or if the buyer is scamming?

**Comment by sidhujag** [comment]
if the seller transfers and the buyer doesnt release, the seller shows the txid and the cert guid and shows it got transferred, the arbiter then releases to the seller... its actually a perfect usecase and its easy to prove the cert was xferred

**Comment by sebastien1234** [comment]
Sure, you can, but you cannot prove what's inside that certificate. It could just say "hahahhaa" instead of having the promised data. Or for example if it's a bitcoin wallet, the seller could use the bitcoin as soon as the cert is transferred and then there's no way for the Arbiter to know who used the wallet or promo code or whatever.

**Comment by sidhujag** [comment]
that is true, if the buyer gets garbage he would have to prove it, by encrypting hahahaha with his public key and showing it points to the same message which is encrypted

**Comment by sidhujag** [comment]
the seller can screw buyer over for digital downloads or transfers of sensitive info, it would just hurt his rep, i think a feedback is probably easy enough and necessary... aswell as a derived rep from escrow usage

**Comment by sebastien1234** [comment]
Yes I agree..

The capture of the HAHAH works but if they give a legit code that they use as soon as it's sold, then the Arbiter wouldn't be able to tell who used it first.

**Comment by sidhujag** [comment]
yea you cant really stop that, reputation is there to give incentive not to do that

**Comment by sidhujag** [comment]
or there needs to be something that is setup that allows someone to know if they have redeemed their certificate, and anything before that is the seller.. when the buyer is ready to view or use the certificate they would click something and look at it, if seller uses it before that then we know its seller thats the culprit... the buyer would use it right away to avoid seller from screwing around.

**Comment by sebastien1234** [comment]
Closing since reputation system is now available close #44
