### ISSUE TITLE
Change Alias Peg name and location

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#46]
Marketplace/Selling/New Offer:

1. Wording and location should be changed; Alias Peg is not an intuitive title; suggestion: Alias for Exchange Rate Peg"

2. Should be at the end of the offer, not at the top (on top will confuse most that don't care).

![image](https://cloud.githubusercontent.com/assets/7034589/14066749/8dcf2e00-f420-11e5-966f-4c1ede03f225.png)

**Comment by dwasyluk** [comment]
Fixed.
