### ISSUE TITLE
offer remains visible when it is in the process of being purchased via escrow

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#47]
purchase an offer via escrow that has only a quantity of 1 

in marketplace/search, offer remains; although sale is not complete, it is pretty much reserved and should no longer show up in the search results.

**Comment by sebastien1234** [comment]
Also, @sidhujag offers remain listed even after escrow is released or refunded (tried both cases); quantity of 1 offers should go to 0 as soon as an escrow is initiated and/or refunded/released.

**Comment by sidhujag** [comment]
mightbe tricky cause offers dont know they are in an escrow. The accept deducts qty which happens as the last step in escrow. Have to think some more on this..

**Comment by sidhujag** [comment]
qty should go to 0 need to look into this one

**Comment by sidhujag** [comment]
I made it so that qty is deducted on escrow initiation and added if escrow is refunded... on escrow accept the qty is not touched... so this needs to be tested

**Comment by sebastien1234** [comment]
@sidhujag this now works as you mentioned, however, it appears that the offer reappears on the marketplace after the refund has been pushed by the merchant (but not yet claimed by the buyer), I'm not sure if that's really an issue, ideally it would only reappear after the refund is claimed by the buyer but I can't think of why that would really be an issue.

**Comment by sidhujag** [comment]
Yeah the qty is refunded aswell so it shows up

**Comment by sebastien1234** [comment]
close #47
