### ISSUE TITLE
No fees going to Arbiter

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#48]
1st case, arbiter refunds escrow transaction

See transaction, initially, arbiter receives 0.00000603 SYS in fees for the escrow, but when he refunds he actually loses 0.00002723 SYS in fees. This also brings up that the Arbiter gets nothing for refunding the transaction. As refunding is an action that is required from the arbiter, he should still get his cut of 0.5% (I also think that should be at least 1%, and even then, a 100$ transaction would only give them $1) which the buyer should be liable for as they elected to use escrow.

![image](https://cloud.githubusercontent.com/assets/7034589/14096344/d667c6c0-f535-11e5-84a4-71f02737f26d.png)

2nd case, arbiter releases escrow:

Arbiter doesn't get anything either and it also cost him more as he gets hit with a fee of 0.00002720 SYS

**Comment by sidhujag** [comment]
make sure you release the refund from the buyer.. then check arbiter wallet. hit refund on buyer wallet.

You cant do 1% it wont really scale. We need a table of escrow amounts the offer owner would fill in.. quitea bit of design needed.

**Comment by sidhujag** [comment]
or perhaps a table controlled by arbiter alias

**Comment by sebastien1234** [comment]
-Not sure what you mean about 1% not scaling, either way for small amounts, say $5, even 1% is a $0.05 payout.
-Yes I think it should be controlled by the arbiter themselves. I'll close #48 and open #49 for the alias controlled escrow fee, and also one for refunding escrow, the status does not change between the buyer refunding, and wording should be "accept refund" if it's really necessary (these things should be automated though).
