### ISSUE TITLE
weird blockchain error

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin2#51]
When trying to update an offer, I received the following error:

![screenshot 2016-03-29 01 34 26](https://cloud.githubusercontent.com/assets/7034589/14098995/9705d67e-f54f-11e5-9b0e-a15ed747219f.png)

Then wallet crashed.

[debug.zip](https://github.com/syscoin/syscoin2/files/192905/debug.zip)

Reopened wallet no problem, tried editing offer again with the SYS_RATES peg and get:

![image](https://cloud.githubusercontent.com/assets/7034589/14099101/6fd73f24-f550-11e5-844c-3efb274479d3.png)

**Comment by sebastien1234** [comment]
-tried also creating a new offer with same wallet and getting same Invalid alias peg error (as soon as I click "new offer")

-tried creating an offer with my second node and got the same "runaway exception" with node 1 and wallet crash

-same with node 3 and 4.

- I blame MR.DANO for all of this.

**Comment by dwasyluk** [comment]
I think I caused this error and I believe it started with this set of steps:

1. create offer using peg1 via walletA at block 1, wait for next block (edited)
2. accept offer via walletB using escrow (arbiter name doesn’t matter), wait for next block
3. (not sure which order this has to happen in, these next 3 steps) update peg1 via walletC making sure to impact a currency offer in #1 uses
4. release escrow via wallet B, wait for next block (edited)
5. release escrow via wallet A

i think it was 4-3-5,  but the order of those last 3 is the important thing and the block occuring between 2/3 of those steps. After i did this 2 of my nodes went down with the error seb added (two involved in tx). Also had this error in log:

`2016-03-29 05:25:09 GUI: PaymentServer::LoadRootCAs: Loaded  163  root certificates
2016-03-29 05:25:09 GUI: TransactionTablePriv::refreshWallet
2016-03-29 05:25:09 ERROR: GetTxOfEscrow() : could not read tx from disk
2016-03-29 05:25:09 ERROR: GetTxOfEscrow() : could not read tx from disk
2016-03-29 05:25:09 ERROR: GetTxOfEscrow() : could not read tx from disk
2016-03-29 05:25:09 ERROR: GetTxOfEscrow() : could not read tx from disk
2016-03-29 05:25:09 ERROR: GetTxOfEscrow() : could not read tx from disk
2016-03-29 05:25:09 ERROR: GetTxOfEscrow() : could not read tx from disk
2016-03-29 05:25:09 ERROR: GetTxOfEscrow() : could not read tx from disk
2016-03-29 05:25:09 ERROR: GetTxOfEscrow() : could not read tx from disk`

**Comment by sidhujag** [comment]
those messages of escrow are normal.... i dont see an actual error.

**Comment by dwasyluk** [comment]
Exact steps:
1. create an alias
2. as soon as the alias creation dialog closes, attempt to create (or update) and offer
3. crash

Note: once crash occurs, after relaunching client will crash every time user attempts to create offer

**Comment by sidhujag** [comment]
I think this was a bad alias value int he form of the alias peg USD rate not being able to be parsed properly... I think its fixed now @sebastien1234 to confirm

**Comment by sebastien1234** [comment]
yup, closes #51
