### ISSUE TITLE
Qty overflow issue / escrow lockup

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin2#53]
Ran into this error while trying to reproduce #51 but I suspect that this may have been the cause of #51 but not sure so logging separately. Using the regtest network to control the block creation I was able to "overflow" an offer qty using an escrow-accept which, once release by both buyer and (attempted release) seller results in this error in the debug.log:

2016-03-29 15:37:48 ERROR: CheckProofOfWork(): hash doesn't match nBits

Steps:
1. create offer with qty 1 via walletA (edited)
2. accept offer 1qty via walletB normal, 1qty via walletB escrow (overflow!), generate 1 block
3. release escrow from walletA, generate 1 block
4. attempt to release escrow from walletB, note error dialog and debug.log error

**Comment by sidhujag** [comment]
that error is normal on regtest network, this is a concurrency issuy
