### ISSUE TITLE
Escrow UX Flow improvement

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin2#58]
Currently managing multiple escrows in which you may have varying role is confusing because buyer/seller/arbiter all see the same 3 enabled options when right clicking an escrow- complete escrow, release escrow, and refund escrow. Also replicated in buttons along the bottom of the wallet frame.

This enhancement would remove the buttons along the bottom of the escrow panel, and the right click menu. A single button on the bottom would replace the existing refund/release/complete buttons that says "Manage Escrow". Right click menu would also be updated as such, and double clicking on the escrow row would automatically open the Manage Escrow dialog.

Manage escrow dialog presents  series of buttons dependent on your role in the escrow transaction.

Buyer: Release Escrow
Arbiter: Release Escrow, Refund Escrow
Seller: Complete Escrow, Refund Escrow

**Comment by sidhujag** [comment]
when a buyer gets refunded he needs to also take action and claim his refund.. so right now he clicks release escrow to release his coins once its refunded. I think its a bit more complex than this.

**Comment by sidhujag** [comment]
In the new flow, there are 10 states you need to test(all states have custom messages):
If escrow is activated:
1) buyer can releas
2) seller can refund
3) arbiter can release or refund

If escrow is released to seller:
4) Buyer cant do anything
5) Seller can claim payment
6) Arbiter cant do anything (receives commission on claim if he did the release)

If escrow is refunded:
7) Buyer can claim refund
8) Seller cant do anything
9) Arbiter cant do anything (receives commission on claim if he did the refund)

If escrow is complete:
10) Buyer/Seller/Arbiter cant do anything.

**Comment by sidhujag** [comment]
please test and close

**Comment by dwasyluk** [comment]
Tested and verified.
