### ISSUE TITLE
Pay Offer

### ISSUE THREAD

**Issue by johnp1954** [syscoin/syscoin2#6]
![image](https://cloud.githubusercontent.com/assets/16462796/13409606/ac4b52b4-df2b-11e5-8111-501454aa0c4a.png)

I think the RED X is wrong makes you think there is a problem

**Comment by sidhujag** [comment]
We don't have error levels, any error that the core will detect it will throw up to the GUI, the gui is just displaying something that went wrong with the acceptance of the offer. In essence, there is a problem it won't accept the offer unless you have filled out the notes field.

**Comment by johnp1954** [comment]
No this dialog comes up as soon as you select an offer before you have had chance to enter anything, should be an information icon

**Comment by sidhujag** [comment]
Got it thanks... changed
