### ISSUE TITLE
imposible send message to seller if wallet lockd by password

### ISSUE THREAD

**Issue by ID453543435** [syscoin/syscoin2#60]
imposible send message to seller if wallet lockd by password

**Comment by sidhujag** [comment]
its not impossible you have to do walletunlock in the console first :)

**Comment by ID453543435** [comment]
what the command?

**Comment by dwasyluk** [comment]
We can slot an enhancement to better expose the route to unlocking the wallet for a period of time but functionally speaking this is working as intended. You must unlock the wallet for a period of time before you can send a message (or read messages)- this is a security feature to protect messages from prying eyes that may simple open your wallet.

To resolve follow the info here: http://syscoin.org/faqs/view-send-messages-encrypted-wallet/

**Comment by ID453543435** [comment]
yes, do slot this enhancement

**Comment by dwasyluk** [comment]
Yep actually ran into another area where this would be helpful yesterday when browsing the marketplace and slotted an official enhancement on the back of that- https://github.com/syscoin/syscoin2/issues/73
