### ISSUE TITLE
console "help" command give wrong infirmaton about commands related to mining

### ISSUE THREAD

**Issue by ID453543435** [syscoin/syscoin2#63]
console "help" command give wrong infirmaton about commands related to mining

**Comment by dwasyluk** [comment]
Typing 'help setgenerate' returns the below which is accurate. Closing. 

`setgenerate generate ( genproclimit )

Set 'generate' true or false to turn generation on or off.
Generation is limited to 'genproclimit' processors, -1 is unlimited.
See the getgenerate call for the current setting.

Arguments:
1. generate         (boolean, required) Set to true to turn on generation, off to turn off.
2. genproclimit     (numeric, optional) Set the processor limit for when generation is on. Can be -1 for unlimited.

Examples:

Set the generation on with a limit of one processor
> syscoin-cli setgenerate true 1

Check the setting
> syscoin-cli getgenerate 

Turn off generation
> syscoin-cli setgenerate false

Using json rpc
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "setgenerate", "params": [true, 1] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/`
